// Generated by Supabase. Do not edit by hand.
// Regenerate with: pnpm --filter @restaurant/database gen:types
//
// Schema source of truth: packages/database/migrations/*.sql

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      branches: {
        Row: {
          address: string | null;
          created_at: string;
          id: string;
          is_active: boolean;
          name: string;
          organization_id: string;
          phone: string | null;
          timezone: string | null;
          updated_at: string;
        };
        Insert: {
          address?: string | null;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          name: string;
          organization_id: string;
          phone?: string | null;
          timezone?: string | null;
          updated_at?: string;
        };
        Update: {
          address?: string | null;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          name?: string;
          organization_id?: string;
          phone?: string | null;
          timezone?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "branches_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      categories: {
        Row: {
          created_at: string;
          id: string;
          is_active: boolean;
          name: string;
          organization_id: string;
          sort_order: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          is_active?: boolean;
          name: string;
          organization_id: string;
          sort_order?: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          is_active?: boolean;
          name?: string;
          organization_id?: string;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "categories_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      ingredients: {
        Row: {
          created_at: string;
          current_cost: number;
          id: string;
          is_active: boolean;
          min_stock_alert: number | null;
          name: string;
          organization_id: string;
          sort_order: number;
          unit: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          current_cost?: number;
          id?: string;
          is_active?: boolean;
          min_stock_alert?: number | null;
          name: string;
          organization_id: string;
          sort_order?: number;
          unit: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          current_cost?: number;
          id?: string;
          is_active?: boolean;
          min_stock_alert?: number | null;
          name?: string;
          organization_id?: string;
          sort_order?: number;
          unit?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ingredients_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      stock_levels: {
        Row: {
          branch_id: string;
          ingredient_id: string;
          organization_id: string;
          quantity: number;
          updated_at: string;
        };
        Insert: {
          branch_id: string;
          ingredient_id: string;
          organization_id: string;
          quantity?: number;
          updated_at?: string;
        };
        Update: {
          branch_id?: string;
          ingredient_id?: string;
          organization_id?: string;
          quantity?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "stock_levels_branch_id_fkey";
            columns: ["branch_id"];
            isOneToOne: false;
            referencedRelation: "branches";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "stock_levels_ingredient_id_fkey";
            columns: ["ingredient_id"];
            isOneToOne: false;
            referencedRelation: "ingredients";
            referencedColumns: ["id"];
          },
        ];
      };
      stock_movements: {
        Row: {
          branch_id: string;
          created_at: string;
          created_by_user_id: string | null;
          id: string;
          ingredient_id: string;
          kind: string;
          notes: string | null;
          order_item_id: string | null;
          organization_id: string;
          quantity_delta: number;
          unit_cost: number;
        };
        Insert: {
          branch_id: string;
          created_at?: string;
          created_by_user_id?: string | null;
          id?: string;
          ingredient_id: string;
          kind: string;
          notes?: string | null;
          order_item_id?: string | null;
          organization_id: string;
          quantity_delta: number;
          unit_cost?: number;
        };
        Update: {
          branch_id?: string;
          created_at?: string;
          created_by_user_id?: string | null;
          id?: string;
          ingredient_id?: string;
          kind?: string;
          notes?: string | null;
          order_item_id?: string | null;
          organization_id?: string;
          quantity_delta?: number;
          unit_cost?: number;
        };
        Relationships: [
          {
            foreignKeyName: "stock_movements_branch_id_fkey";
            columns: ["branch_id"];
            isOneToOne: false;
            referencedRelation: "branches";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "stock_movements_ingredient_id_fkey";
            columns: ["ingredient_id"];
            isOneToOne: false;
            referencedRelation: "ingredients";
            referencedColumns: ["id"];
          },
        ];
      };
      invoices: {
        Row: {
          created_at: string;
          currency: string;
          customer_name: string | null;
          customer_tax_id: string | null;
          discount_amount: number;
          id: string;
          invoice_number: number;
          issued_at: string;
          order_id: string;
          organization_id: string;
          subtotal: number;
          tax_amount: number;
          total: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          currency: string;
          customer_name?: string | null;
          customer_tax_id?: string | null;
          discount_amount: number;
          id?: string;
          invoice_number: number;
          issued_at?: string;
          order_id: string;
          organization_id: string;
          subtotal: number;
          tax_amount: number;
          total: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          currency?: string;
          customer_name?: string | null;
          customer_tax_id?: string | null;
          discount_amount?: number;
          id?: string;
          invoice_number?: number;
          issued_at?: string;
          order_id?: string;
          organization_id?: string;
          subtotal?: number;
          tax_amount?: number;
          total?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "invoices_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: true;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "invoices_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      payments: {
        Row: {
          amount: number;
          created_at: string;
          id: string;
          method: string;
          order_id: string;
          organization_id: string;
          received_by_user_id: string;
          reference: string | null;
          updated_at: string;
        };
        Insert: {
          amount: number;
          created_at?: string;
          id?: string;
          method: string;
          order_id: string;
          organization_id: string;
          received_by_user_id: string;
          reference?: string | null;
          updated_at?: string;
        };
        Update: {
          amount?: number;
          created_at?: string;
          id?: string;
          method?: string;
          order_id?: string;
          organization_id?: string;
          received_by_user_id?: string;
          reference?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "payments_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      memberships: {
        Row: {
          branch_id: string | null;
          created_at: string;
          id: string;
          is_active: boolean;
          organization_id: string;
          role: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          branch_id?: string | null;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          organization_id: string;
          role: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          branch_id?: string | null;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          organization_id?: string;
          role?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "memberships_branch_id_fkey";
            columns: ["branch_id"];
            isOneToOne: false;
            referencedRelation: "branches";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "memberships_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      order_items: {
        Row: {
          created_at: string;
          id: string;
          line_total: number | null;
          notes: string | null;
          order_id: string;
          organization_id: string;
          product_id: string;
          product_name_snapshot: string;
          quantity: number;
          unit_price: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          line_total?: number | null;
          notes?: string | null;
          order_id: string;
          organization_id: string;
          product_id: string;
          product_name_snapshot: string;
          quantity: number;
          unit_price: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          line_total?: number | null;
          notes?: string | null;
          order_id?: string;
          organization_id?: string;
          product_id?: string;
          product_name_snapshot?: string;
          quantity?: number;
          unit_price?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "order_items_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "order_items_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "order_items_product_id_fkey";
            columns: ["product_id"];
            isOneToOne: false;
            referencedRelation: "products";
            referencedColumns: ["id"];
          },
        ];
      };
      order_status_history: {
        Row: {
          changed_at: string;
          changed_by_user_id: string | null;
          from_status: string;
          id: string;
          notes: string | null;
          order_id: string;
          organization_id: string;
          to_status: string;
        };
        Insert: {
          changed_at?: string;
          changed_by_user_id?: string | null;
          from_status: string;
          id?: string;
          notes?: string | null;
          order_id: string;
          organization_id: string;
          to_status: string;
        };
        Update: {
          changed_at?: string;
          changed_by_user_id?: string | null;
          from_status?: string;
          id?: string;
          notes?: string | null;
          order_id?: string;
          organization_id?: string;
          to_status?: string;
        };
        Relationships: [
          {
            foreignKeyName: "order_status_history_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "order_status_history_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      orders: {
        Row: {
          branch_id: string;
          cancelled_at: string | null;
          created_at: string;
          delivered_at: string | null;
          discount_amount: number;
          id: string;
          notes: string | null;
          opened_at: string;
          order_number: number;
          organization_id: string;
          paid_at: string | null;
          ready_at: string | null;
          status: string;
          subtotal: number;
          table_id: string | null;
          tax_amount: number;
          total: number;
          updated_at: string;
          waiter_user_id: string;
        };
        Insert: {
          branch_id: string;
          cancelled_at?: string | null;
          created_at?: string;
          delivered_at?: string | null;
          discount_amount?: number;
          id?: string;
          notes?: string | null;
          opened_at?: string;
          order_number?: number;
          organization_id: string;
          paid_at?: string | null;
          ready_at?: string | null;
          status?: string;
          subtotal?: number;
          table_id?: string | null;
          tax_amount?: number;
          total?: number;
          updated_at?: string;
          waiter_user_id: string;
        };
        Update: {
          branch_id?: string;
          cancelled_at?: string | null;
          created_at?: string;
          delivered_at?: string | null;
          discount_amount?: number;
          id?: string;
          notes?: string | null;
          opened_at?: string;
          order_number?: number;
          organization_id?: string;
          paid_at?: string | null;
          ready_at?: string | null;
          status?: string;
          subtotal?: number;
          table_id?: string | null;
          tax_amount?: number;
          total?: number;
          updated_at?: string;
          waiter_user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "orders_branch_id_fkey";
            columns: ["branch_id"];
            isOneToOne: false;
            referencedRelation: "branches";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "orders_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "orders_table_id_fkey";
            columns: ["table_id"];
            isOneToOne: false;
            referencedRelation: "tables";
            referencedColumns: ["id"];
          },
        ];
      };
      organizations: {
        Row: {
          created_at: string;
          currency: string;
          id: string;
          name: string;
          owner_user_id: string;
          slug: string;
          tax_id: string | null;
          timezone: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          currency?: string;
          id?: string;
          name: string;
          owner_user_id: string;
          slug: string;
          tax_id?: string | null;
          timezone?: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          currency?: string;
          id?: string;
          name?: string;
          owner_user_id?: string;
          slug?: string;
          tax_id?: string | null;
          timezone?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tables: {
        Row: {
          branch_id: string;
          capacity: number;
          created_at: string;
          id: string;
          is_active: boolean;
          name: string;
          organization_id: string;
          sort_order: number;
          status: string;
          updated_at: string;
        };
        Insert: {
          branch_id: string;
          capacity?: number;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          name: string;
          organization_id: string;
          sort_order?: number;
          status?: string;
          updated_at?: string;
        };
        Update: {
          branch_id?: string;
          capacity?: number;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          name?: string;
          organization_id?: string;
          sort_order?: number;
          status?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tables_branch_id_fkey";
            columns: ["branch_id"];
            isOneToOne: false;
            referencedRelation: "branches";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tables_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      products: {
        Row: {
          category_id: string;
          cost: number;
          created_at: string;
          description: string | null;
          id: string;
          image_url: string | null;
          is_active: boolean;
          name: string;
          organization_id: string;
          price: number;
          sort_order: number;
          updated_at: string;
        };
        Insert: {
          category_id: string;
          cost?: number;
          created_at?: string;
          description?: string | null;
          id?: string;
          image_url?: string | null;
          is_active?: boolean;
          name: string;
          organization_id: string;
          price: number;
          sort_order?: number;
          updated_at?: string;
        };
        Update: {
          category_id?: string;
          cost?: number;
          created_at?: string;
          description?: string | null;
          id?: string;
          image_url?: string | null;
          is_active?: boolean;
          name?: string;
          organization_id?: string;
          price?: number;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "products_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "products_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      create_organization_with_branch: {
        Args: {
          branch_address: string;
          branch_name: string;
          branch_phone: string;
          branch_timezone: string;
          org_currency: string;
          org_name: string;
          org_slug: string;
          org_tax_id: string;
          org_timezone: string;
        };
        Returns: Json;
      };
      find_user_by_email: {
        Args: { target_email: string };
        Returns: string;
      };
      list_org_members: {
        Args: { target_org_id: string };
        Returns: {
          branch_id: string;
          created_at: string;
          email: string;
          full_name: string;
          is_active: boolean;
          membership_id: string;
          role: string;
          user_id: string;
        }[];
      };
      user_can_manage_org: {
        Args: { target_org_id: string };
        Returns: boolean;
      };
      user_has_role_in_org: {
        Args: { required_role: string; target_org_id: string };
        Returns: boolean;
      };
      user_org_ids: {
        Args: never;
        Returns: string[];
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
